apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  labels:
    app: demo
    tier: server
spec:
  selector:
    matchLabels:
      app: demo
      tier: server
  template:
    metadata:
      name: pg
      labels:
        app: demo
        tier: server
    spec:
      containers:
        - name: pg
          image: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
              name: pg-tcp
          envFrom:
            - configMapRef:
                name: pg-config