apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  type: LoadBalancer
  ports:
    - port: 10000
      targetPort: client-http
      protocol: TCP
      name: client
    - port: 8080
      targetPort: spring-http
      protocol: TCP
      name: spring
  selector:
    app: demo