apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
data:
  POSTGRES_USER: test
  POSTGRES_PASSWORD: test
  POSTGRES_DB: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-conf
data:
  DB_USERNAME: test
  DB_PASSWORD: test
  DB_DRIVER: org.postgresql.Driver
  DB_URL: jdbc:postgresql://pg-svc:5432/test