spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:~/test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USERNAME:sa}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    password: ${DB_PASSWORD:""}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true