spring:
  datasource:
    url: jdbc:h2:mem:~/test;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
    password:
    platform: org.hibernate.dialect.H2Dialect
    initialization-mode: embedded
management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true